# Generated by Django 5.0.1 on 2024-02-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='many_posts', to='article.category', verbose_name='categories'),
        ),
    ]
